django_learning/urls.py
from django.contrib import admin
from django.urls import path, include
from login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("index/", views.index),
    path("", views.index),
    path("polls/", include("polls.urls"))
]

polls/urls.py
from django.urls import path
from . import views


app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="question_detail"),
    path("<int:question_id>/result/", views.results, name="question_results"),
    path("<int:question_id>/vote/", views.votes, name="choice_vote")
]

login/models.py
from django.db import models


class UserInfo(models.Model):
    username = models.CharField(max_length=32)
    password = models.CharField(max_length=32)

polls/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_content = models.CharField(max_length=255)
    publish_time = models.DateTimeField("data published")

    def __str__(self):
        return "{'question_content': " + self.question_content + ", 'publish_time': " + str(self.publish_time) + " }"

    def was_publish_recently(self):
        return self.publish_time >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_content = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return "{ 'Question': " + self.question.__str__() + ", 'choice_content': " + self.choice_content + \
               ", 'votes': " + str(self.votes) + " }"


class Person(models.Model):
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)

login/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from login import models


# user_list = []


def index(request):
    # return HttpResponse("hello world...")
    # return render(request, "index.html")
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        # current_user = {"username": username, "password": password}
        # user_list.append(current_user)

        models.UserInfo.objects.create(username=username, password=password)
    user_list = models.UserInfo.objects.all()
    return render(request, "index.html", {"data": user_list})

polls/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.http import HttpResponse
from django.template import loader

from .models import Question


def index(request):
    question_list = get_list_or_404(Question)
    content = {
        "question_list": question_list
    }
    return render(request=request, template_name="polls/index.html", context=content)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {
        "question": question
    }
    return render(request, "polls/detail.html", context)


def results(request, question_id):
    resp = " you're looking at the result of question %s "
    return HttpResponse(resp % question_id)


def votes(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    choice = question.choice_set.get(pk=request.POST.get("choice"))
    choice.votes += 1
    choice.save()
    return HttpResponse(" you're voting for choice %s " % request.POST.get("choice"))

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detail</title>
</head>
<body>
<h1>{{ question.question_content }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:choice_vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_content }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">
</head>
<body>
{% if question_list %}
    <ul>
        {% for question in question_list %}
            <li><a href="{% url 'polls:question_detail' question.id %}">{{ question.question_content }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <script src="/static/js/jquery-3.3.1.min.js"></script>
</head>
<body>
     <h1>用户输入：</h1>
    <form action="/index/" method="post">
        {% csrf_token %}
        用户名：<input type="text" name="username" /><br />
        密码：<input type="password" name="password" /><br />
        <input type="submit" value="提交" />
    </form>

    <h1>用户展示：</h1>
        <table border="1">
            <thead>
                <tr>用户名</tr>
                <tr>密码</tr>
            </thead>
            <tbody>
                {% for item in data %}
                <tr>
                    <td>{{ item.username }}</td>
                    <td>{{ item.password }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
</body>
</html>